classes = {
    0: 'Give Way',
    1: 'No Straight Ahead',
    2: 'One Way',
    3: 'One Way',
    4: 'Vehicles Prohibited in Both Directions',
    5: 'Cycle Prohibited',
    6: 'Truck Prohibited',
    7: 'Pedestrian Prohibited',
    8: 'Bullock Carts Prohibited',
    9: 'Hand Carts Prohibited',
    10: 'All Motor Vehicles Prohibited',
    11: 'Height limit',
    12: 'Load Limit',
    13: 'Axle Load Limit',
    14: 'Length Limit',
    15: 'Left Turn Prohibited',
    16: 'Right Turn Prohibited',
    17: 'Overtaking Prohibited',
    18: 'Maximum Speed Limit (90 km/h)',
    19: 'Maximum Speed limit (110 km/h)',
    20: 'Horn Prohibited',
    21: 'No Parking',
    22: 'No Stopping',
    23: 'Compulsory Turn Left',
    24: 'Compulsory Turn Right',
    25: 'Steep Descent',
    26: 'Steep Ascent',
    27: 'Narrow Road Ahead',
    28: 'Narrow Bridge',
    29: 'Unprotected quay',
    30: 'Speed Breaker',
    31: 'Dangerous Dip',
    32: 'Loose Gravel',
    33: 'Falling Rocks',
    34: 'Cattle',
    35: 'Cross Roads',
    36: 'Side Road',
    37: 'Side Road',
    38: 'Y-Intersection',
    39: 'Y-Intersection',
    40: 'T-Intersection',
    41: 'Y-Intersection',
    42: 'Staggered Intersections',
    43: 'Staggered Intersections',
    44: 'Round About',
    45: 'Guarded Railway Crossing',
    46: 'Unguarded Level Crossing Ahead',
    47: 'School',
    48: 'Slippery Road',
    49: 'Men at Work',
    50: 'Pedestrian Subway',
    51: 'Park This Side',
    52: 'Bus Stop',
    53: 'First Aid post',
    54: 'Telephone',
    55: 'Petrol Pump',
    56: 'Resting Place',
    57: 'Eating Place',
    58: 'Light Refreshments'
}